version: '3'

services:
  mazi-backend:
    build:
      context: .
      target: development
    command: npm run start:dev:no-docker
    image: mazi-backend
    container_name: mazi-backend
    expose:
      - "${PORT-3000}"
    ports:
      - "${PORT-3000}:${PORT-3000}"
      - 9229:9229
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  default:
    external:
      name: nginx-proxy-net