version: '3'

services:
  mazi-backend:
    build:
      context: .
      target: development
    command: npm run start:dev:no-docker
    image: mazi-backend
    container_name: mazi-backend
    ports:
      - "3000:80"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # healthcheck:
    #   test: [ "curl", "-f", "http://127.0.0.1/api/v1.0/health" ]
    #   timeout: 20s
    #   retries: 10

networks:
  default:
    external:
      name: nginx-proxy-net